### ISSUE TITLE
Not able to use programl 

### ISSUE THREAD

**Issue by harshitalpha** [ChrisCummins/ProGraML#187] opened 2021-11-17 04:58 UTC
Hi,
I am trying to use `programl` for generating control flow graph for some `c++` files, I have installed it using 
```
pip3 install programl
```
I am trying to run following code
```
import programl as pg
G = pg.from_cpp(""""
#include <iostream>
int main(int argc, char** argv) {
	std::cout << "Hello, world!" << std::endl;
	return 0;
}
""")
print(type(G))
net = pg.to_networkx(G)
pg.save_graphs('file.data', [G])
```
But i am getting following error
```
Using backend: pytorch
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    G = pg.from_cpp(""""
  File "/home/harshit/.local/lib/python3.8/site-packages/programl/create_ops.py", line 175, in from_cpp
    return _run_one(srcs)
  File "/home/harshit/.local/lib/python3.8/site-packages/programl/create_ops.py", line 172, in _run_one
    return _graph_from_subprocess(process, stdout, stderr)
  File "/home/harshit/.local/lib/python3.8/site-packages/programl/create_ops.py", line 51, in _graph_from_subprocess
    raise GraphCreationError(stderr.decode("utf-8"))
programl.exceptions.GraphCreationError: /home/harshit/.local/lib/python3.8/site-packages/programl/bin/clang2graph-10: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
There is a file `clang2graph-10` in my system at the particular location. 
Please let me know what can be the potential problem?

Thanks and Regards
Harshit Singhal

**Comment by ChrisCummins** [comment] 2021-11-17 11:30
Hi @harshitalpha,

The error is because your system is missing a library called `libtinfo.so.5` that ProGraML depends on. Can you please confirm what operating system you are using (on linux, paste the output of `cat /etc/os-release`).

I have enountered this same error before, either because `libtinfo.so.5` was not installed, or because a different version like `libtinfo.so.6` was installed. Here are a few suggestions on StackOverflow ranging from a package install to just symlinking an equivalent library: 
https://stackoverflow.com/questions/48674104/clang-error-while-loading-shared-libraries-libtinfo-so-5-cannot-open-shared-o

Let me know if any of them work :-)

Cheers,
Chris

**Comment by harshitalpha** [comment] 2021-11-17 14:00
Hi,
I am using `ububtu 20.04`, and here's the output for `cat /etc/os-release` 
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
I guess i have `libtinfo.so.5` file in my system, I have tried to locate this file by following command
```
locate libtinfo
```
and i got following output
```
/snap/core18/2128/lib/x86_64-linux-gnu/libtinfo.so.5
/snap/core18/2128/lib/x86_64-linux-gnu/libtinfo.so.5.9
/snap/core18/2128/usr/share/doc/libtinfo5
/snap/core18/2128/usr/share/doc/libtinfo5/changelog.Debian.gz
/snap/core18/2128/usr/share/doc/libtinfo5/copyright
/snap/core18/2246/lib/x86_64-linux-gnu/libtinfo.so.5
/snap/core18/2246/lib/x86_64-linux-gnu/libtinfo.so.5.9
/snap/core18/2246/usr/share/doc/libtinfo5
/snap/core18/2246/usr/share/doc/libtinfo5/changelog.Debian.gz
/snap/core18/2246/usr/share/doc/libtinfo5/copyright
/usr/lib/x86_64-linux-gnu/libtinfo.a
/usr/lib/x86_64-linux-gnu/libtinfo.so
/usr/lib/x86_64-linux-gnu/libtinfo.so.6
/usr/lib/x86_64-linux-gnu/libtinfo.so.6.2
/usr/share/doc/libtinfo6
/usr/share/doc/libtinfo6/FAQ
/usr/share/doc/libtinfo6/TODO.Debian
/usr/share/doc/libtinfo6/changelog.Debian.gz
/usr/share/doc/libtinfo6/copyright
/var/lib/dpkg/info/libtinfo6:amd64.list
/var/lib/dpkg/info/libtinfo6:amd64.md5sums
/var/lib/dpkg/info/libtinfo6:amd64.shlibs
/var/lib/dpkg/info/libtinfo6:amd64.symbols
/var/lib/dpkg/info/libtinfo6:amd64.triggers
```
Please let me know the solution 

Thanks and Regards
Harshit Singhal

**Comment by ChrisCummins** [comment] 2021-11-17 14:46
Okay great, I would suggest just symlinking the different version of libtinfo you already have and seeing if that works:

```
sudo ln -s libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5
```

Failing that, you could try copying the version that you have installed in `/snap`:

```
sudo cp /snap/core18/2128/lib/x86_64-linux-gnu/libtinfo.so.5 /usr/lib/x86_64-linux-gnu
sudo cp /snap/core18/2128/lib/x86_64-linux-gnu/libtinfo.so.5.9 /usr/lib/x86_64-linux-gnu
```

Cheers,
Chris

**Comment by harshitalpha** [comment] 2021-11-18 07:39
Hi,
I have tried the above solution, but after that, my system is suddenly shuts down and it is not booting up now. 
What can I do to fix this issue?

Thanks and Regards
Harshit Singhal

**Comment by ChrisCummins** [comment] 2021-11-18 17:53
Blimey, that's strange!

The only thing I could suggest is to try build ProGraML from source: https://github.com/ChrisCummins/ProGraML/blob/development/INSTALL.md#building-from-source

I can't reproduce the issue on my local machine or on the CI job runners, which also use Ubuntu 20.04.

Cheers,
Chris

**Comment by harshitalpha** [comment] 2021-11-23 10:24
Hi, 
I actually have to reinstall Ubuntu from scratch, when I investigated the problem I found out that the command which is supposed to copy from the `/snap` folder, actually deleted everything inside the `/snap` folder. That's why Ubuntu is not booting up. This is Strange, but I am able to get my data back. Now I can try the above solution. 
I will update you when I am done with this.

Thanks and Regards 
Harshit Singhal

**Comment by harshitalpha** [comment] 2021-11-24 13:44
Hi, 
I just need to run the following command
```
sudo apt install libtinfo.so.5
```
and everything runs fine. 
I have another question regarding the `programl`, is there any way to convert the control flow graph back to the source code? If there is please let me know the way to do it. 

Thanks and Regards
Harshit Singhal

**Comment by harshitalpha** [comment] 2021-11-24 17:25
Hi,
Also, Can we get the complexity of the source code by just looking at the graph it generated?  If yes, please let me know how can we do it. 

Thanks and Regards
Harshit Singhal

**Comment by ChrisCummins** [comment] 2021-11-30 01:03
> Hi, I just need to run the following command
> 
> ```
> sudo apt install libtinfo.so.5
> ```
> 
> and everything runs fine.

Great, glad to hear!

> I have another question regarding the `programl`, is there any way to convert the control flow graph back to the source code? If there is please let me know the way to do it.

No, not currently. ProGraML is constructed from LLVM-IR, and I don't do anything to keep track of the original source code locations. It *would* be possible to modify ProGraML to make this easier by using debug information, let me know if you would be interested in implementing this and we can discuss further.

> Also, Can we get the complexity of the source code by just looking at the graph it generated?

Depends how you want to measure complexity. You could calculate [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of the control flow graph, or aggregate some other statistics over the graph. Or do you mean the asymptotic time complexity?

Cheers,
Chris

**Comment by harshitalpha** [comment] 2021-11-30 03:06
Hey,
I am talking about asymptotic time complexity. 

Thanks and Regards
Harshit Singhal

**Comment by ChrisCummins** [comment] 2021-11-30 10:52
I'm not aware of any LLVM analyses for estimating a program's time complexity. A quick google unearthed [this project](https://github.com/demontiejr/asymptus), but it targets a very old version of LLVM so would likely need updating. I expect you will need to manually label your algorithms, or perhaps there could be analysis tools that operate on a higher level programming language that you could then lower to LLVM-IR.

Cheers,
Chris

**Comment by ChrisCummins** [comment] 2021-11-30 10:53
Closing this issue as OP fixed the problem above.

Cheers,
Chris

**Closed as completed by ChrisCummins** 2021-11-30 10:53 UTC
Labels: Bug
