### ISSUE TITLE
Tensorflow issue

### ISSUE THREAD

**Issue by akash-isu** [ChrisCummins/ProGraML#138] opened 2020-10-28 05:16 UTC
I'm getting this error while trying bazel test //programl. Can anyone help me with this issue? I have tensorflow 2.3.1 installed. Python version 3.8.5

Could not find a version that satisfies the requirement tensorflow>=1.14.0 (from -r /root/.cache/bazel/_bazel_root/2788c7a9ba5c9ff287d0935fbb5fc6a8/external/programl/requirements.txt (line 22)) (from versions: )
No matching distribution found for tensorflow>=1.14.0 (from -r /root/.cache/bazel/_bazel_root/2788c7a9ba5c9ff287d0935fbb5fc6a8/external/programl/requirements.txt (line 22))

**Comment by ChrisCummins** [comment] 2020-10-28 06:36
Hi @akash-isu, unfortunately I haven't got around to updating the build system for Tensorflow 2.x. In the meantime, can you please checkout the `wip/drop_tf` branch and try again?

```sh
$ git fetch --all
$ git checkout origin/wip/drop_tf -b wip/drop_tf
$ bazel test //programl/...
```

Cheers,
Chris

**Comment by akash-isu** [comment] 2020-10-28 17:59
I tried using this branch. Now I keep getting these issues. Did not find much online related to this.

ERROR: An error occurred during the fetch of repository 'grpc_py_deps':
   pip_import failed: Collecting grpcio==1.20.0 (from -r /root/.cache/bazel/_bazel_root/6361a55dce3b1692160849ab52284221/external/build_stack_rules_proto/python/requirements.txt (line 1))

ERROR: no such package '@grpc_py_deps//': pip_import failed: Collecting grpcio==1.20.0 (from -r /root/.cache/bazel/_bazel_root/6361a55dce3b1692160849ab52284221/external/build_stack_rules_proto/python/requirements.txt (line 1))

Thanks,
Akash

**Comment by ChrisCummins** [comment] 2020-10-30 15:49
Hi Akash, yes, that's a tricky error :) I took a quick look at hacking out the build dependencies so that you won't hit this error. If you pull the `wip/drop_tf` branch you should see an update that will fix this issue. Given that you have time pressure, feel free to follow up with me on email if you're still having build problems!

Closing this as the original problem is a dupe of #76.

Cheers,
Chris

**Closed as completed by ChrisCummins** 2020-10-30 15:49 UTC
