### ISSUE TITLE
TensorFlow 1.x not supported on Python 3.8

### ISSUE THREAD

**Issue by TharinduRusira** [ChrisCummins/ProGraML#76] opened 2020-08-11 01:10 UTC
Hi, I'm trying to build with `bazel test //programl/...` and it fails with the following error. It looks like `tensorflow==1.14.0` is not found on my pip channels. 
OS Ubuntu 20.04
Python 3.8.2
Pip 20.2.1
Bazel 3.0.0

On a related note, will it be possible to upgrade tf version from 1.14 to something more recent without breaking the build?

```
INFO: Call stack for the definition of repository 'programl_requirements' which is a pip_import (rule definition at /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/rules_python/python/pip.bzl:51:14):
 - <builtin>
 - /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/rules_python/python/pip.bzl:128:5
 - /home/tharindu/programl/WORKSPACE:37:1
ERROR: An error occurred during the fetch of repository 'programl_requirements':
   pip_import failed: Collecting cycler==0.10.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
  Saved ./cycler-0.10.0-py2.py3-none-any.whl
Collecting decorator==4.3.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
  Saved ./decorator-4.3.0-py2.py3-none-any.whl
Collecting gast==0.2.2. (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/4e/35/11749bf99b2d4e3cceb4d55ca22590b0d7c2c62b9de38ac4a4a7f4687421/gast-0.2.2.tar.gz
Collecting GPUtil==1.4.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ed/0e/5c61eedde9f6c87713e89d794f01e378cfd9565847d4576fa627d758c554/GPUtil-1.4.0.tar.gz
Collecting Keras==2.3.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/ad/fd/6bfe87920d7f4fd475acd28500a42482b6b84479832bdc0fe9e589a60ceb/Keras-2.3.1-py2.py3-none-any.whl
  Saved ./Keras-2.3.1-py2.py3-none-any.whl
Collecting kiwisolver==1.0.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/31/60/494fcce70d60a598c32ee00e71542e52e27c978e5f8219fae0d4ac6e2864/kiwisolver-1.0.1.tar.gz
Collecting matplotlib==2.2.0rc1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/38/76/99650ec91a3013fb05f7b2d0a40d9339a4577db48f7c33a6a2149a6613de/matplotlib-2.2.0rc1.tar.gz
Collecting networkx==2.2 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/f3/f4/7e20ef40b118478191cec0b58c3192f822cace858c19505c7670961b76b2/networkx-2.2.zip
Collecting numpy==1.16.4 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/d3/4b/f9f4b96c0b1ba43d28a5bdc4b64f0b9d3fbcf31313a51bc766942866a7c7/numpy-1.16.4.zip
Collecting pandas==0.24.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/81/fd/b1f17f7dc914047cd1df9d6813b944ee446973baafe8106e4458bfb68884/pandas-0.24.1.tar.gz
Collecting pathlib==1.0.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz
Collecting protobuf==3.6.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/77/78/a7f1ce761e2c738e209857175cd4f90a8562d1bde32868a8cd5290d58926/protobuf-3.6.1-py2.py3-none-any.whl
  Saved ./protobuf-3.6.1-py2.py3-none-any.whl
Collecting psutil==5.4.5 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/14/a2/8ac7dda36eac03950ec2668ab1b466314403031c83a95c5efc81d2acf163/psutil-5.4.5.tar.gz
Collecting pyparsing==2.2.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
  Saved ./pyparsing-2.2.0-py2.py3-none-any.whl
Collecting python-dateutil==2.6.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/4b/0d/7ed381ab4fe80b8ebf34411d14f253e1cf3e56e2820ffa1d8844b23859a2/python_dateutil-2.6.1-py2.py3-none-any.whl
  Saved ./python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pytz==2018.3 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/3c/80/32e98784a8647880dedf1f6bf8e2c91b195fe18fdecc6767dcf5104598d6/pytz-2018.3-py2.py3-none-any.whl
  Saved ./pytz-2018.3-py2.py3-none-any.whl
Collecting PyYAML==4.2b4 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/a8/c6/a8d1555e795dbd0375c3c93b576ca13bbf139db51ea604afa19a2c35fc03/PyYAML-4.2b4.tar.gz
Collecting scikit-learn==0.20.3 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/f1/cb/3297656b9a3cce0cb60c691d568225fc025d47d3eb668b3c480211801a52/scikit-learn-0.20.3.tar.gz
Collecting scipy==1.2.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/a9/b4/5598a706697d1e2929eaf7fe68898ef4bea76e4950b9efbe1ef396b8813a/scipy-1.2.1.tar.gz
Collecting seaborn==0.9.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/a8/76/220ba4420459d9c4c9c9587c6ce607bf56c25b3d3d2de62056efe482dadc/seaborn-0.9.0-py3-none-any.whl
  Saved ./seaborn-0.9.0-py3-none-any.whl
Collecting tensorflow==1.14.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 21))
 (  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement tensorflow==1.14.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 21)) (from versions: )
No matching distribution found for tensorflow==1.14.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 21))
)
ERROR: no such package '@programl_requirements//': pip_import failed: Collecting cycler==0.10.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
  Saved ./cycler-0.10.0-py2.py3-none-any.whl
Collecting decorator==4.3.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
  Saved ./decorator-4.3.0-py2.py3-none-any.whl
Collecting gast==0.2.2. (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/4e/35/11749bf99b2d4e3cceb4d55ca22590b0d7c2c62b9de38ac4a4a7f4687421/gast-0.2.2.tar.gz
Collecting GPUtil==1.4.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ed/0e/5c61eedde9f6c87713e89d794f01e378cfd9565847d4576fa627d758c554/GPUtil-1.4.0.tar.gz
Collecting Keras==2.3.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/ad/fd/6bfe87920d7f4fd475acd28500a42482b6b84479832bdc0fe9e589a60ceb/Keras-2.3.1-py2.py3-none-any.whl
  Saved ./Keras-2.3.1-py2.py3-none-any.whl
Collecting kiwisolver==1.0.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/31/60/494fcce70d60a598c32ee00e71542e52e27c978e5f8219fae0d4ac6e2864/kiwisolver-1.0.1.tar.gz
Collecting matplotlib==2.2.0rc1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/38/76/99650ec91a3013fb05f7b2d0a40d9339a4577db48f7c33a6a2149a6613de/matplotlib-2.2.0rc1.tar.gz
Collecting networkx==2.2 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/f3/f4/7e20ef40b118478191cec0b58c3192f822cace858c19505c7670961b76b2/networkx-2.2.zip
Collecting numpy==1.16.4 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/d3/4b/f9f4b96c0b1ba43d28a5bdc4b64f0b9d3fbcf31313a51bc766942866a7c7/numpy-1.16.4.zip
Collecting pandas==0.24.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/81/fd/b1f17f7dc914047cd1df9d6813b944ee446973baafe8106e4458bfb68884/pandas-0.24.1.tar.gz
Collecting pathlib==1.0.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz
Collecting protobuf==3.6.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/77/78/a7f1ce761e2c738e209857175cd4f90a8562d1bde32868a8cd5290d58926/protobuf-3.6.1-py2.py3-none-any.whl
  Saved ./protobuf-3.6.1-py2.py3-none-any.whl
Collecting psutil==5.4.5 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/14/a2/8ac7dda36eac03950ec2668ab1b466314403031c83a95c5efc81d2acf163/psutil-5.4.5.tar.gz
Collecting pyparsing==2.2.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
  Saved ./pyparsing-2.2.0-py2.py3-none-any.whl
Collecting python-dateutil==2.6.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/4b/0d/7ed381ab4fe80b8ebf34411d14f253e1cf3e56e2820ffa1d8844b23859a2/python_dateutil-2.6.1-py2.py3-none-any.whl
  Saved ./python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pytz==2018.3 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/3c/80/32e98784a8647880dedf1f6bf8e2c91b195fe18fdecc6767dcf5104598d6/pytz-2018.3-py2.py3-none-any.whl
  Saved ./pytz-2018.3-py2.py3-none-any.whl
Collecting PyYAML==4.2b4 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/a8/c6/a8d1555e795dbd0375c3c93b576ca13bbf139db51ea604afa19a2c35fc03/PyYAML-4.2b4.tar.gz
Collecting scikit-learn==0.20.3 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/f1/cb/3297656b9a3cce0cb60c691d568225fc025d47d3eb668b3c480211801a52/scikit-learn-0.20.3.tar.gz
Collecting scipy==1.2.1 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/a9/b4/5598a706697d1e2929eaf7fe68898ef4bea76e4950b9efbe1ef396b8813a/scipy-1.2.1.tar.gz
Collecting seaborn==0.9.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/a8/76/220ba4420459d9c4c9c9587c6ce607bf56c25b3d3d2de62056efe482dadc/seaborn-0.9.0-py3-none-any.whl
  Saved ./seaborn-0.9.0-py3-none-any.whl
Collecting tensorflow==1.14.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 21))
 (  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement tensorflow==1.14.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 21)) (from versions: )
No matching distribution found for tensorflow==1.14.0 (from -r /home/tharindu/.cache/bazel/_bazel_tharindu/32e7df8edab156150aace45b26f7d94e/external/programl/requirements.txt (line 21))
)
INFO: Elapsed time: 11.066s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

`pip install tensorflow==1.14.0` fails with,
```
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.14.0
```

**Comment by ChrisCummins** [comment] 2020-08-11 23:00
Hi Tharindu, thanks for the comprehensive report! This is indeed a bug - in fact, both the TensorFlow and Torch versions I have specified no longer install. I will update the dependencies and test with the latest versions. In the meantime, the hotfix is, in the root of this repo:

```sh
$ sed 's/^tensorflow==/tensorflow>=/ ; s/^torch==1.3/torch==1.4/' -i requirements.txt
```

Then proceed as normal:

```sh
$ bazel test //programl/...
```

Disclaimer: I was able to reproduce the error and have tested that the build succeeds with this fix, but there may be API deprecations that will cause errors further down the line. I'll keep an eye on it.

Cheers,
Chris

**Comment by TharinduRusira** [comment] 2020-08-13 22:17
Hi Chris,
Thanks for the quick fix. 
However, I had to downgrade my Python (3.8-->3.6) and use Anaconda channels to get all requirements built.
Python 3.8 couldn't build scipy==1.2.1 and this particular version seems to be a strict requisite for labm8==2020.06.07. 

Tharindu

**Comment by ChrisCummins** [comment] 2020-08-13 22:24
Hi @TharinduRusira, thanks for following up and sharing your workaround! Yes, there seem to be some odd issues with py3.8. I'll investigate further and post a fix when I find one. I imagine my requirements.txt file is overly strict on the accepted versions, and the transient deps from labm8 are a bit of a headache. Closing this since it seems you have fixed the issue, but please re-open/file a new issue if required! :)

Cheers,
Chris

**Comment by gchaperon** [comment] 2020-08-14 07:04
Hi! Just had the same problem and i wanted to share that  tensorflow 1.x just wasn't released for python 3.8 (https://pypi.org/project/tensorflow/1.15.3/#files) so it is normal that its not possible to install it with pip (as far as I know pip searches the pypi by default).

I just used a python 3.6 virtualenv and had no further problem.
Maybe a quick solution would be to only allow python 3.{6,7}, i think tensorflow made braking changes in version 2.x.

Thank you very much for the work! Cheers

**Comment by ChrisCummins** [comment] 2020-08-14 08:12
Hi @gchaperon,  I worried it might be something like this, thanks for confirming :)

I realized it is premature to close this issue as others will be affected. Note to self: before merging #77 I need to add test coverage for the current `tf.compat.v1` API uses.

Cheers,
Chris

**Comment by Zacharias030** [comment] 2020-08-14 08:36
This is also my understanding of the situation!
Am 14. Aug. 2020, 09:04 +0200 schrieb Gabriel Chaperon Burgos <notifications@github.com>:

**Comment by Zacharias030** [comment] 2020-08-14 08:37
*Tensorflow 1.x
Am 14. Aug. 2020, 10:13 +0200 schrieb Chris Cummins <notifications@github.com>:

**Comment by ChrisCummins** [comment] 2020-08-14 08:46
> *Tensorflow 1.x

Thanks ;)

**Comment by ChrisCummins** [comment] 2020-11-19 23:51
Killed Tensorflow dependency in #142, and remaining work superseded by #124.

Cheers,
Chris

**Closed by ChrisCummins** 2020-11-19 23:51 UTC
Labels: Bug, Testing & Tooling
