### ISSUE TITLE
Recreating the algorithm classification results

### ISSUE THREAD

**Issue by ajovanovic1** [ChrisCummins/ProGraML#155] opened 2021-02-08 18:42 UTC
Greetings Chris and other collaborators,

I have recently read the ProGraML paper and I would like to reproduce the Algorithm Classification (section 6.3) results.
However, when I clone the [feature/classifyapp_81_chris](https://github.com/ChrisCummins/ProGraML/tree/feature/classifyapp_81_chris) branch and try to run the script [run.py](https://github.com/ChrisCummins/ProGraML/blob/feature/classifyapp_81_chris/programl/task/graph_level_classification/run.py) with
```bash
python run.py --help
```
I get an error
```python
File "/home/user/ProGraML/programl/task/graph_level_classification/run.py", line 55, in <module>
    from .dataloader import NodeLimitedDataLoader
ImportError: attempted relative import with no known parent package
```
Then I manually built the proto packages as in #107 and after running
```bash
python -m programl.task.graph_level_classication.run --help
```
from the root directory I got the error
```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/ProGraML-chris/programl/task/graph_level_classification/run.py", line 60, in <module>
    from .configs import (
  File "/home/user/ProGraML-chris/programl/task/graph_level_classification/configs.py", line 17, in <module>
    from programl.task.graph_level_classification.dataset import AblationVocab
  File "/home/user/ProGraML-chris/programl/task/graph_level_classification/dataset.py", line 16, in <module>
    from programl.graph.format.py import cdfg as cdfg_format
  File "/home/user/ProGraML-chris/programl/graph/format/py/cdfg.py", line 26, in <module>
    GRAPH2CDFG = bazelutil.DataPath("programl/cmd/graph2cdfg")
  File "/home/user/virtual-environments/programl-venv/lib/python3.6/site-packages/labm8/py/bazelutil.py", line 74, in DataPath
    raise FileNotFoundError(f"No such file or directory: '{path}'")
FileNotFoundError: No such file or directory: 'programl/cmd/graph2cdfg'
```

I also tried building the package using bazel by running the command
```bash
bazel build //programl/task/graph_level_classification:all
```
but I had the same error again after running the script. I'd be glad if you could help me with running the program.

## OTHER NOTES
I am running Python 3.6.9 on Ubuntu 18.04

**Comment by ChrisCummins** [comment] 2021-02-16 18:59
Hi @ajovanovic1, thank you for the detailed bug report. Unfortunately I just haven't found the time to complete work on porting the graph classification code yet, the pull request you tried out is still in a work-in-progress state.

Closing a dupe of #81 but please sign up there for notifications so that I can ping you once it's done :)

Cheers,
Chris

**Closed as completed by ChrisCummins** 2021-02-16 18:59 UTC
